# Generated by Django 4.1.3 on 2022-12-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, default='image.jpg', upload_to=''),
        ),
    ]
